server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://assemblock.cf8wcw6w2dp0.ap-southeast-2.rds.amazonaws.com:3306/assemblock_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: kukchaewon
    password: {password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

kakao:
  rest-api-key: {rest-api}
  redirect-uri: http://localhost:8080/callback

jwt:
  secret-key: { jwtsecretkey }
  # 액세스 토큰 만료 시간
  access-token-expiration-ms: 1800000
  # 리프레시 토큰 만료 시간
  refresh-token-expiration-ms: 604800000